-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN     "discountPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "originalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "gstType" SET DEFAULT 'PERCENTAGE';
